# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# install! 'cocoapods', :deterministic_uuids => false

target 'TempProject' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TempProject
  # 'node_modules'目录一般位于根目录中
  # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTText',
  'RCTNetwork',
  'RCTImage',
  'RCTWebSocket', # 这个模块是用于调试功能的
  # 在这里继续添加你所需要的模块
  ]
  pod 'AFNetworking'

    target 'TempProjectTests' do
        end
    target 'TempProjectUITests' do
        end



end




